apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pgo
  namespace: postgres-operator
spec:
  chart: oci://registry.developers.crunchydata.com/crunchydata/pgo
  targetNamespace: postgres-operator
